server:
  port: 9092
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/
          Predicates:
            - Path=/api/**
          filters:
            - JwtAuthenticationFilter


        - id: identity-service
          uri: http://localhost:8080/
          Predicates:
              - Path=/auth/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
